import { Category, Product, Order } from "@/types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "herramientas-manuales",
    name: "Discos de Corte & Manuales",
    slug: "herramientas-manuales",
    description: "Discos abrasivos Fortek, Atouan, discos diamantados, llaves, alicates y destornilladores.",
    icon: "Wrench",
    image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80",
    order: 1,
    productCount: 42,
    featured: true,
  },
  {
    id: "herramientas-electricas",
    name: "Herramientas Eléctricas",
    slug: "herramientas-electricas",
    description: "Taladros percutores 20V, amoladoras angulares, pulidoras, sierras y rotomartillos.",
    icon: "Zap",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
    order: 2,
    productCount: 28,
    featured: true,
  },
  {
    id: "plomeria-tuberias",
    name: "Plomería, Tuberías y Riego",
    slug: "plomeria-tuberias",
    description: "Tubería PVC presión y sanitaria Pavco/Tubrica, válvulas, griferías y riego por goteo.",
    icon: "Droplets",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&auto=format&fit=crop&q=80",
    order: 3,
    productCount: 36,
    featured: true,
  },
  {
    id: "pinturas-selladores",
    name: "Pinturas & Selladores",
    slug: "pinturas-selladores",
    description: "Pinturas de caucho Montana AV-2000, esmaltes sintéticos, siliconas, brochas y rodillos.",
    icon: "Paintbrush",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80",
    order: 4,
    productCount: 24,
    featured: true,
  },
  {
    id: "electricidad-iluminacion",
    name: "Electricidad & Iluminación",
    slug: "electricidad-iluminacion",
    description: "Reflectores LED exteriores Sylvania, bombillos de alta potencia, cables y breakers.",
    icon: "Lightbulb",
    image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&auto=format&fit=crop&q=80",
    order: 5,
    productCount: 30,
    featured: true,
  },
  {
    id: "cerrajeria-herrajes",
    name: "Cerrajería & Seguridad",
    slug: "cerrajeria-herrajes",
    description: "Cerraduras tubulares Cisa, cerrojos de seguridad, candados de hierro y bisagras.",
    icon: "Lock",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    order: 6,
    productCount: 22,
    featured: true,
  },
  {
    id: "construccion",
    name: "Construcción & Albañilería",
    slug: "construccion",
    description: "Cemento gris Portland Vencemos, pegamento para baldosas, estuco y discos diamantados.",
    icon: "HardHat",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
    order: 7,
    productCount: 32,
    featured: true,
  },
  {
    id: "repuestos-electrodomesticos",
    name: "Repuestos y Jardinería",
    slug: "repuestos-electrodomesticos",
    description: "Dispositivos de riego automático para plantas, mangueras y acoples de jardinería.",
    icon: "Cpu",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    order: 8,
    productCount: 16,
    featured: false,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-disco-corte-fortek-dsc02",
    name: "Disco de corte extra fino con hundido 4/2x 1/16 x 7/8 DSC02 Fortek",
    slug: "disco-de-corte-extra-fino-con-hundido-4-2-fortek-dsc02",
    description: "Disco de corte abrasivo extra fino con centro hundido para metal y acero inoxidable. Gran velocidad de corte con mínimo desperdicio de material y bajo calentamiento. Diámetro 4-1/2\" (115 mm), espesor 1.6 mm.",
    category: "herramientas-manuales",
    categoryName: "Discos de Corte & Manuales",
    brand: "FORTEK",
    sku: "DSC02-FORTEK",
    basePrice: 1.00,
    originalPrice: 1.50,
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 468,
    isFeatured: true,
    isOffer: true,
    rating: 5.0,
    reviewsCount: 12,
    specs: {
      "Dimensiones": "4-1/2\" x 1/16\" x 7/8\" (115 x 1.6 x 22.2 mm)",
      "Perfil": "Centro Hundido / Deprimido Tipo 27",
      "Aplicación": "Metal, Acero al carbono e Inoxidable",
      "Velocidad Máx": "13.300 RPM (80 m/s)",
      "Refuerzo": "Doble malla de fibra de vidrio de alta tenacidad",
    },
    tags: ["disco", "corte", "fortek", "esmeril", "metal", "abrasivo"],
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-25T14:30:00Z",
  },
  {
    id: "prod-disco-corte-plano-fortek-dsc01",
    name: "Disco de corte extra fino plano 4/2x1/16x7/8 DSC01 Fortek",
    slug: "disco-de-corte-extra-fino-plano-4-2-fortek-dsc01",
    description: "Disco de corte plano de alto rendimiento fabricado con grano de óxido de aluminio reforzado con doble malla para cortes rectos precisos y seguros en perfiles, láminas y cabillas.",
    category: "herramientas-manuales",
    categoryName: "Discos de Corte & Manuales",
    brand: "FORTEK",
    sku: "DSC01-FORTEK",
    basePrice: 1.00,
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 111,
    isFeatured: true,
    isOffer: false,
    rating: 4.9,
    reviewsCount: 3,
    specs: {
      "Dimensiones": "4-1/2\" x 1/16\" x 7/8\" (115 x 1.6 x 22.2 mm)",
      "Perfil": "Plano Tipo 41",
      "Seguridad": "Reforzado con fibra de vidrio",
      "Velocidad Máx": "13.300 RPM",
    },
    tags: ["disco", "plano", "fortek", "corte", "metal"],
    createdAt: "2026-08-02T10:00:00Z",
    updatedAt: "2026-08-25T15:00:00Z",
  },
  {
    id: "prod-disco-corte-acero-atouan",
    name: "Disco de corte acero convencional Atouan",
    slug: "disco-de-corte-acero-convencional-atouan",
    description: "Disco de corte industrial para acero y metales ferrosos. Rendimiento consistente y corte limpio para trabajos continuos de herrería, cerrajería y mantenimiento industrial.",
    category: "herramientas-manuales",
    categoryName: "Discos de Corte & Manuales",
    brand: "ATOUAN",
    sku: "ATN-CRTE-01",
    basePrice: 1.00,
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-atn-115", name: "4-1/2\" (115 mm)", sku: "ATN-115", price: 1.00, stock: 137 },
      { id: "v-atn-180", name: "7\" (180 mm)", sku: "ATN-180", price: 2.20, stock: 45 },
      { id: "v-atn-230", name: "9\" (230 mm)", sku: "ATN-230", price: 3.50, stock: 30 },
    ],
    stock: 212,
    isFeatured: true,
    isOffer: false,
    rating: 4.8,
    reviewsCount: 8,
    specs: {
      "Marca": "Atouan Industrial",
      "Material": "Óxido de Aluminio Grado A",
      "Uso": "Corte de cabillas, tubos estructurales, pletinas y vigas",
    },
    tags: ["disco", "atouan", "corte", "acero", "herreria"],
    createdAt: "2026-08-03T11:00:00Z",
    updatedAt: "2026-08-25T16:00:00Z",
  },
  {
    id: "prod-disco-corte-extra-fino-atouan",
    name: "Disco de corte extra fino Atouan",
    slug: "disco-de-corte-extra-fino-atouan",
    description: "Diseñado para cortes de precisión ultra rápidos con rebaba mínima. Ideal para perfilería delgada de aluminio y acero inoxidable sin deformar el material.",
    category: "herramientas-manuales",
    categoryName: "Discos de Corte & Manuales",
    brand: "ATOUAN",
    sku: "ATN-FINO-115",
    basePrice: 1.00,
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-atn-f-115", name: "4-1/2\" x 1.0 mm", sku: "ATN-F115", price: 1.00, stock: 24 },
      { id: "v-atn-f-125", name: "5\" x 1.2 mm", sku: "ATN-F125", price: 1.30, stock: 18 },
    ],
    stock: 42,
    isFeatured: false,
    isOffer: false,
    rating: 4.7,
    reviewsCount: 5,
    specs: {
      "Espesor": "1.0 mm extra delgado",
      "Corte": "Precisión libre de rebabas",
    },
    tags: ["disco", "fino", "atouan", "corte"],
    createdAt: "2026-08-04T12:00:00Z",
    updatedAt: "2026-08-25T16:15:00Z",
  },
  {
    id: "prod-riego-goteo-powerfik",
    name: "Dispositivo de riego por goteo automático para plantas Powerfik",
    slug: "dispositivo-de-riego-por-goteo-automatico-plantas-powerfik",
    description: "Válvula de riego por goteo graduable compatible con botellas plásticas estándar. Permite calibrar el flujo de agua de 0 a 60 segundos por gota para regar automáticamente tus macetas de 1 a 15 días continuos.",
    category: "repuestos-electrodomesticos",
    categoryName: "Repuestos y Jardinería",
    brand: "POWERFIK",
    sku: "PWK-RIEGO-01",
    basePrice: 1.00,
    originalPrice: 1.80,
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 16,
    isFeatured: true,
    isOffer: true,
    rating: 4.9,
    reviewsCount: 9,
    specs: {
      "Material": "Polipropileno (PP) de alta durabilidad",
      "Compatibilidad": "Rosca universal para botellas de agua/refresco",
      "Regulación": "Llave de paso milimétrica",
    },
    tags: ["riego", "goteo", "jardin", "powerfik", "plantas", "hogar"],
    createdAt: "2026-08-05T09:00:00Z",
    updatedAt: "2026-08-25T17:00:00Z",
  },
  {
    id: "prod-taladro-percutor-total-20v",
    name: "Taladro Percutor Inalámbrico 20V Total Tools con 2 Baterías y Maletín",
    slug: "taladro-percutor-inalambrico-20v-total-tools-kit",
    description: "Taladro percutor inalámbrico de 20V con motor de alto torque (45 Nm), 2 velocidades mecánicas, luz LED integrada y función de percusión para mampostería y concreto. Incluye 2 baterías de litio 20V, cargador rápido y maletín de transporte.",
    category: "herramientas-electricas",
    categoryName: "Herramientas Eléctricas",
    brand: "TOTAL",
    sku: "TIDLI20012",
    basePrice: 58.00,
    originalPrice: 68.00,
    images: [
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-tot-std", name: "Kit 2 Baterías 2.0Ah + Maletín", sku: "TIDLI-2.0", price: 58.00, stock: 22 },
      { id: "v-tot-pro", name: "Kit Pro 2 Baterías 4.0Ah + 50 Accesorios", sku: "TIDLI-4.0", price: 79.00, stock: 10 },
    ],
    stock: 32,
    isFeatured: true,
    isOffer: true,
    rating: 4.9,
    reviewsCount: 28,
    specs: {
      "Voltaje": "20V Litio-Ion",
      "Torque Máximo": "45 Nm (18+1+1 ajustes)",
      "Mandril": "10 mm (3/8\") metálico autoajustable",
      "Velocidad": "0-400 / 0-1500 RPM",
      "Garantía": "1 Año Oficial Total Tools",
    },
    tags: ["taladro", "total", "inalambrico", "herramientas", "20v"],
    createdAt: "2026-08-06T10:00:00Z",
    updatedAt: "2026-08-25T18:00:00Z",
  },
  {
    id: "prod-esmeril-angular-ingco-750w",
    name: "Esmeriladora / Pulidora Angular 4-1/2\" 750W Ingco Industrial",
    slug: "esmeriladora-pulidora-angular-4-1-2-750w-ingco",
    description: "Amoladora angular con motor blindado de 750W a 12.000 RPM. Mango ergonómico auxiliar de 2 posiciones con traba de eje para cambio rápido de disco. Ideal para desbaste y corte de metales y mampostería.",
    category: "herramientas-electricas",
    categoryName: "Herramientas Eléctricas",
    brand: "INGCO",
    sku: "AG75028",
    basePrice: 32.00,
    originalPrice: 38.00,
    images: [
      "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 45,
    isFeatured: true,
    isOffer: true,
    rating: 4.8,
    reviewsCount: 15,
    specs: {
      "Potencia": "750 Watts",
      "Velocidad": "12.000 RPM",
      "Diámetro de disco": "115 mm (4-1/2 pulg)",
      "Voltaje": "110V - 120V / 60Hz",
    },
    tags: ["esmeril", "pulidora", "ingco", "corte", "amoladora"],
    createdAt: "2026-08-07T11:00:00Z",
    updatedAt: "2026-08-25T18:30:00Z",
  },
  {
    id: "prod-cerradura-pomo-cisa",
    name: "Cerradura de Pomo Tubular de Seguridad Cisa Acero Inoxidable",
    slug: "cerradura-de-pomo-tubular-seguridad-cisa-acero",
    description: "Cerradura de pomo con mecanismo de cilindro de latón de alta precisión y pestillo ajustable de 60 a 70 mm. Acabado en acero inoxidable satinado resistente a la corrosión y uso continuo.",
    category: "cerrajeria-herrajes",
    categoryName: "Cerrajería & Seguridad",
    brand: "CISA",
    sku: "CISA-POMO-SS",
    basePrice: 12.50,
    images: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-cisa-ent", name: "Entrada Principal (Con Llave)", sku: "CISA-ENT", price: 12.50, stock: 35 },
      { id: "v-cisa-ban", name: "Baño / Privacidad (Con Botón)", sku: "CISA-BAN", price: 11.00, stock: 28 },
      { id: "v-cisa-pas", name: "Paso / Dormitorio", sku: "CISA-PAS", price: 11.00, stock: 20 },
    ],
    stock: 83,
    isFeatured: true,
    isOffer: false,
    rating: 5.0,
    reviewsCount: 19,
    specs: {
      "Material": "Acero Inoxidable 304 y Cilindro de Latón",
      "Espesor de puerta": "35 mm a 45 mm estándar",
      "Incluye": "3 llaves de seguridad y tornillos de fijación",
    },
    tags: ["cerradura", "cisa", "pomo", "seguridad", "puerta"],
    createdAt: "2026-08-08T14:00:00Z",
    updatedAt: "2026-08-25T19:00:00Z",
  },
  {
    id: "prod-tubo-pvc-pavco-presion",
    name: "Tubo PVC Presión Agua Blanca 1/2\" x 3m Pavco / Tubrica",
    slug: "tubo-pvc-presion-agua-blanca-pavco-tubrica",
    description: "Tubería de PVC para distribución de agua potable a presión en instalaciones residenciales y comerciales. Alta resistencia química, paredes lisas anti-incrustaciones y unión solvente 100% estanca.",
    category: "plomeria-tuberias",
    categoryName: "Plomería, Tuberías y Riego",
    brand: "PAVCO",
    sku: "TUB-PVC-12",
    basePrice: 3.50,
    images: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-tub-12", name: "1/2\" x 3 metros", sku: "TUB-12-3M", price: 3.50, stock: 150 },
      { id: "v-tub-34", name: "3/4\" x 3 metros", sku: "TUB-34-3M", price: 4.80, stock: 95 },
      { id: "v-tub-10", name: "1\" x 3 metros", sku: "TUB-10-3M", price: 6.50, stock: 60 },
    ],
    stock: 305,
    isFeatured: true,
    isOffer: false,
    rating: 4.9,
    reviewsCount: 14,
    specs: {
      "Material": "PVC rígido no plastificado",
      "Presión nominal": "500 PSI a 23°C",
      "Longitud": "3 Metros por tramo",
      "Norma": "ASTM D-1785 / COVENIN",
    },
    tags: ["tubo", "pvc", "pavco", "tubrica", "agua", "plomeria"],
    createdAt: "2026-08-09T08:00:00Z",
    updatedAt: "2026-08-25T19:30:00Z",
  },
  {
    id: "prod-pintura-caucho-montana-av2000",
    name: "Pintura de Caucho Interior / Exterior AV-2000 Montana (Galón)",
    slug: "pintura-caucho-interior-exterior-av2000-montana",
    description: "Pintura emulsionada de acabado mate aterciopelado con excelente lavabilidad, alto poder de cubrimiento y máxima resistencia al clima tropical. Ideal para paredes interiores y fachadas exteriores.",
    category: "pinturas-selladores",
    categoryName: "Pinturas & Selladores",
    brand: "MONTANA",
    sku: "MON-AV2000-GL",
    basePrice: 18.00,
    originalPrice: 22.00,
    images: [
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-mon-bla-1g", name: "Blanco Nieve - 1 Galón", sku: "AV2000-BLA-1G", price: 18.00, stock: 40 },
      { id: "v-mon-bla-cun", name: "Blanco Nieve - Cuñete (4 Galones)", sku: "AV2000-BLA-4G", price: 68.00, stock: 15 },
      { id: "v-mon-mar-1g", name: "Marfil - 1 Galón", sku: "AV2000-MAR-1G", price: 18.00, stock: 25 },
      { id: "v-mon-gri-1g", name: "Gris Platino - 1 Galón", sku: "AV2000-GRI-1G", price: 18.00, stock: 20 },
    ],
    stock: 100,
    isFeatured: true,
    isOffer: true,
    rating: 5.0,
    reviewsCount: 31,
    specs: {
      "Rendimiento": "35 a 40 m² por galón a una mano",
      "Secado": "30 minutos al tacto / 3 horas para segunda mano",
      "Acabado": "Mate Lavable",
    },
    tags: ["pintura", "montana", "caucho", "av2000", "pared", "galon"],
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-25T20:00:00Z",
  },
  {
    id: "prod-reflector-led-50w-sylvania",
    name: "Reflector LED Exterior 50W Alta Luminosidad IP65 Sylvania",
    slug: "reflector-led-exterior-50w-alta-luminosidad-sylvania",
    description: "Reflector LED plano con disipador de aluminio inyectado y cristal templado de alta resistencia. Grado IP65 a prueba de lluvia para fachadas, estacionamientos, galpones y patios residenciales.",
    category: "electricidad-iluminacion",
    categoryName: "Electricidad & Iluminación",
    brand: "SYLVANIA",
    sku: "SYL-REF-50W",
    basePrice: 12.00,
    originalPrice: 15.00,
    images: [
      "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-syl-6500k", name: "Luz Blanca Fría (6500K)", sku: "SYL-50W-BLA", price: 12.00, stock: 50 },
      { id: "v-syl-3000k", name: "Luz Cálida (3000K)", sku: "SYL-50W-CAL", price: 12.00, stock: 25 },
    ],
    stock: 75,
    isFeatured: false,
    isOffer: true,
    rating: 4.8,
    reviewsCount: 11,
    specs: {
      "Potencia": "50 Watts (4.500 Lúmenes)",
      "Voltaje": "85V - 265V Multi-voltaje",
      "Protección": "IP65 para intemperie total",
      "Vida útil": "25.000 horas continuas",
    },
    tags: ["reflector", "led", "sylvania", "luz", "iluminacion", "exterior"],
    createdAt: "2026-08-11T13:00:00Z",
    updatedAt: "2026-08-25T20:15:00Z",
  },
  {
    id: "prod-cemento-gris-vencemos",
    name: "Cemento Gris Tipo Portland Uso General (Saco 42.5 Kg)",
    slug: "cemento-gris-tipo-portland-uso-general-vencemos",
    description: "Cemento gris Portland de fraguado rápido y alta resistencia inicial y final para pegado de bloques, vaciado de losas, frisos, pisos y columnas estructurales.",
    category: "construccion",
    categoryName: "Construcción & Albañilería",
    brand: "VENCEMOS",
    sku: "CEM-VENC-42",
    basePrice: 7.50,
    images: [
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 600,
    isFeatured: true,
    isOffer: false,
    rating: 5.0,
    reviewsCount: 42,
    specs: {
      "Peso neto": "42.5 Kilogramos por saco",
      "Norma": "COVENIN 28 / Tipo I",
      "Uso": "Obras civiles, albañilería y pisos",
    },
    tags: ["cemento", "vencemos", "construccion", "obra", "albañileria", "saco"],
    createdAt: "2026-08-12T07:00:00Z",
    updatedAt: "2026-08-25T20:30:00Z",
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1001",
    orderNumber: "MH-2026-1001",
    customer: {
      name: "Alejandro Mendoza",
      phone: "04141234567",
      city: "Caracas",
      address: "Av. Francisco de Miranda, Edif. Centro Plaza",
      notes: "Pago por Zelle al recibir",
    },
    items: [
      {
        productId: "prod-disco-corte-fortek-dsc02",
        productName: "Disco de corte extra fino con hundido Fortek",
        slug: "disco-de-corte-extra-fino-con-hundido-4-2-fortek-dsc02",
        sku: "DSC02-FORTEK",
        image: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
        price: 1.00,
        quantity: 10,
        maxStock: 468,
      },
      {
        productId: "prod-taladro-percutor-total-20v",
        productName: "Taladro Percutor Inalámbrico 20V Total Tools",
        slug: "taladro-percutor-inalambrico-20v-total-tools-kit",
        sku: "TIDLI-2.0",
        image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
        price: 58.00,
        quantity: 1,
        variantId: "v-tot-std",
        variantName: "Kit 2 Baterías 2.0Ah + Maletín",
        maxStock: 22,
      },
    ],
    subtotal: 68.00,
    total: 68.00,
    status: "completado",
    channel: "whatsapp_web",
    createdAt: "2026-08-24T15:20:00Z",
    updatedAt: "2026-08-24T17:40:00Z",
  },
  {
    id: "ord-1002",
    orderNumber: "MH-2026-1002",
    customer: {
      name: "Taller Mecánico Los Próceres",
      phone: "04249876543",
      city: "Valencia",
      address: "Zona Industrial El Bosque, Galpón 8",
      notes: "Factura fiscal y pago vía Pago Móvil",
    },
    items: [
      {
        productId: "prod-cemento-gris-vencemos",
        productName: "Cemento Gris Tipo Portland Uso General (Saco 42.5 Kg)",
        slug: "cemento-gris-tipo-portland-uso-general-vencemos",
        sku: "CEM-VENC-42",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
        price: 7.50,
        quantity: 20,
        maxStock: 600,
      },
    ],
    subtotal: 150.00,
    total: 150.00,
    status: "atendido",
    channel: "whatsapp_web",
    createdAt: "2026-08-25T09:10:00Z",
    updatedAt: "2026-08-25T10:15:00Z",
  },
];