import { Category, Product, Order } from "@/types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "herramientas-electricas",
    name: "Herramientas Eléctricas",
    slug: "herramientas-electricas",
    description: "Taladros, pulidoras, sierras, rotomartillos y lijadoras de alta potencia.",
    icon: "Zap",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
    order: 1,
    productCount: 18,
    featured: true,
  },
  {
    id: "herramientas-manuales",
    name: "Herramientas Manuales",
    slug: "herramientas-manuales",
    description: "Llaves, destornilladores, alicates, martillos y juegos de copas profesionales.",
    icon: "Wrench",
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?w=800&auto=format&fit=crop&q=80",
    order: 2,
    productCount: 24,
    featured: true,
  },
  {
    id: "plomeria-tuberias",
    name: "Plomería y Tuberías",
    slug: "plomeria-tuberias",
    description: "Tubería PVC, CPVC, griferías, válvulas, pegamentos y accesorios hidrosanitarios.",
    icon: "Droplets",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&auto=format&fit=crop&q=80",
    order: 3,
    productCount: 32,
    featured: true,
  },
  {
    id: "pinturas-selladores",
    name: "Pinturas y Selladores",
    slug: "pinturas-selladores",
    description: "Vinilos tipo 1 y 2, esmaltes, siliconas, selladores de grietas, brochas y rodillos.",
    icon: "Paintbrush",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80",
    order: 4,
    productCount: 15,
    featured: true,
  },
  {
    id: "electricidad-iluminacion",
    name: "Electricidad e Iluminación",
    slug: "electricidad-iluminacion",
    description: "Cables certificados, breakers, paneles LED, tomas, interruptores y extensiones de uso rudo.",
    icon: "Lightbulb",
    image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&auto=format&fit=crop&q=80",
    order: 5,
    productCount: 28,
    featured: true,
  },
  {
    id: "repuestos-electrodomesticos",
    name: "Repuestos Electrodomésticos",
    slug: "repuestos-electrodomesticos",
    description: "Mangueras de lavadora, acoples de licuadora, empaques, termostatos y resistencias.",
    icon: "Cpu",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    order: 6,
    productCount: 19,
    featured: false,
  },
  {
    id: "cerrajeria-herrajes",
    name: "Cerrajería y Herrajes",
    slug: "cerrajeria-herrajes",
    description: "Cerraduras de seguridad, candados de alta resistencia, bisagras, manijas y correderas.",
    icon: "Lock",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    order: 7,
    productCount: 22,
    featured: false,
  },
  {
    id: "construccion",
    name: "Construcción",
    slug: "construccion",
    description: "Cemento, estuco, discos de corte diamantados, mallas, varillas y equipos de protección.",
    icon: "HardHat",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
    order: 8,
    productCount: 30,
    featured: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-taladro-percutor-dewalt",
    name: "Taladro Percutor Inalámbrico 20V DeWalt Brushless",
    slug: "taladro-percutor-inalambrico-20v-dewalt-brushless",
    description: "Taladro percutor compacto de 20V MAX* con motor sin escobillas (Brushless) para mayor durabilidad y tiempo de funcionamiento. Incluye 2 baterías de 2.0Ah, cargador rápido y maletín de transporte de alto impacto.",
    category: "herramientas-electricas",
    categoryName: "Herramientas Eléctricas",
    brand: "DeWalt",
    sku: "DCD7781D2-B3",
    basePrice: 589000,
    originalPrice: 650000,
    images: [
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v1", name: "Kit Estándar (2 Baterías 2.0Ah + Maletín)", sku: "DCD778-STD", price: 589000, stock: 12 },
      { id: "v2", name: "Kit Pro (2 Baterías 4.0Ah + Set 15 Brocas)", sku: "DCD778-PRO", price: 749000, stock: 6 },
    ],
    stock: 18,
    isFeatured: true,
    isOffer: true,
    rating: 4.9,
    reviewsCount: 34,
    specs: {
      "Voltaje": "20V MAX",
      "Mandril": "1/2 pulgada (13mm) metálico",
      "Velocidad": "0-500 / 0-1750 RPM",
      "Impactos por minuto": "0-29750 IPM",
      "Garantía": "3 Años oficial DeWalt",
    },
    tags: ["inalámbrico", "taladro", "profesional", "dewalt"],
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
  },
  {
    id: "prod-pulidora-angular-makita",
    name: "Esmeriladora Angular 4-1/2\" 840W Makita",
    slug: "esmeriladora-angular-4-1-2-840w-makita",
    description: "Amoladora angular con potente motor de 840W, diseño ergonómico y cuerpo delgado para fácil agarre. Cuenta con sistema de laberinto para proteger el motor del polvo y virutas metálicas.",
    category: "herramientas-electricas",
    categoryName: "Herramientas Eléctricas",
    brand: "Makita",
    sku: "9557HNG",
    basePrice: 285000,
    originalPrice: 320000,
    images: [
      "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-110v", name: "110V (Uso estándar taller/hogar)", sku: "9557-110V", price: 285000, stock: 15 },
      { id: "v-220v", name: "220V (Uso industrial pesado)", sku: "9557-220V", price: 295000, stock: 8 },
    ],
    stock: 23,
    isFeatured: true,
    isOffer: false,
    rating: 4.8,
    reviewsCount: 19,
    specs: {
      "Potencia": "840 Watts",
      "Diámetro de disco": "4-1/2 pulgada (115 mm)",
      "Velocidad": "11.000 RPM",
      "Cable": "2.5 metros industrial reforzado",
      "Garantía": "1 Año Makita",
    },
    tags: ["pulidora", "esmeril", "corte", "makita"],
    createdAt: "2026-08-05T11:00:00Z",
    updatedAt: "2026-08-22T09:15:00Z",
  },
  {
    id: "prod-juego-llaves-stanley",
    name: "Juego de Llaves Mixtas Métricas y Pulgadas Stanley (20 Piezas)",
    slug: "juego-de-llaves-mixtas-metricas-y-pulgadas-stanley-20-piezas",
    description: "Juego completo de llaves combinadas fabricadas en acero cromo vanadio forjado para máxima resistencia. Acabado cromado anticorrosivo con sistema Maxi-Drive que evita el desgaste de tuercas.",
    category: "herramientas-manuales",
    categoryName: "Herramientas Manuales",
    brand: "Stanley",
    sku: "STMT74108",
    basePrice: 165000,
    originalPrice: 190000,
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 25,
    isFeatured: true,
    isOffer: true,
    rating: 4.9,
    reviewsCount: 42,
    specs: {
      "Material": "Acero Cromo Vanadio (Cr-V)",
      "Contenido": "10 Llaves métricas (8-19mm) + 10 Llaves SAE (1/4\" - 3/4\")",
      "Estuche": "Bandeja enrollable de lona industrial",
      "Garantía": "Garantía de por vida Stanley",
    },
    tags: ["llaves", "stanley", "mecanica", "herramientas"],
    createdAt: "2026-08-03T14:00:00Z",
    updatedAt: "2026-08-24T12:00:00Z",
  },
  {
    id: "prod-tubo-pvc-pavco",
    name: "Tubería Sanitaria y Presión PVC Pavco Wavin (Tramos de 6 Metros)",
    slug: "tuberia-sanitaria-y-presion-pvc-pavco-wavin-tramos-6m",
    description: "Tubería de PVC de alta durabilidad y resistencia al impacto para instalaciones hidrosanitarias y redes de agua potable domiciliarias. Cumple con norma técnica NTC 382 y NTC 1087.",
    category: "plomeria-tuberias",
    categoryName: "Plomería y Tuberías",
    brand: "Pavco Wavin",
    sku: "TUB-PVC-PAV",
    basePrice: 38500,
    images: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-pvc-12", name: "Presión 1/2\" x 6m", sku: "PVC-PRES-12", price: 38500, stock: 120 },
      { id: "v-pvc-34", name: "Presión 3/4\" x 6m", sku: "PVC-PRES-34", price: 49900, stock: 85 },
      { id: "v-pvc-1", name: "Presión 1\" x 6m", sku: "PVC-PRES-10", price: 68000, stock: 40 },
      { id: "v-sanit-2", name: "Sanitaria 2\" x 6m", sku: "PVC-SAN-20", price: 72000, stock: 50 },
      { id: "v-sanit-3", name: "Sanitaria 3\" x 6m", sku: "PVC-SAN-30", price: 115000, stock: 35 },
      { id: "v-sanit-4", name: "Sanitaria 4\" x 6m", sku: "PVC-SAN-40", price: 154000, stock: 30 },
    ],
    stock: 360,
    isFeatured: true,
    isOffer: false,
    rating: 5.0,
    reviewsCount: 16,
    specs: {
      "Longitud": "6 Metros por tramo",
      "Material": "Policloruro de Vinilo Rígido",
      "Certificación": "Icontec NTC / ISO 9001",
    },
    tags: ["tubo", "pvc", "plomeria", "pavco", "agua"],
    createdAt: "2026-08-02T08:00:00Z",
    updatedAt: "2026-08-25T16:00:00Z",
  },
  {
    id: "prod-pintura-koraza-pintuco",
    name: "Pintura Impermeable Koraza Protección Extrema Pintuco",
    slug: "pintura-impermeable-koraza-proteccion-extrema-pintuco",
    description: "Pintura base agua para exteriores de máxima durabilidad y resistencia a los rayos UV, lluvia y formación de hongos. Crea una barrera elastomérica que sella microfisuras.",
    category: "pinturas-selladores",
    categoryName: "Pinturas y Selladores",
    brand: "Pintuco",
    sku: "PIN-KOR-5G",
    basePrice: 112000,
    images: [
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-blanco-1g", name: "Blanco Puro - 1 Galón", sku: "KOR-BLA-1G", price: 112000, stock: 30 },
      { id: "v-blanco-5g", name: "Blanco Puro - Cuñete (5 Galones)", sku: "KOR-BLA-5G", price: 495000, stock: 12 },
      { id: "v-gris-1g", name: "Gris Cemento - 1 Galón", sku: "KOR-GRI-1G", price: 112000, stock: 18 },
      { id: "v-gris-5g", name: "Gris Cemento - Cuñete (5 Galones)", sku: "KOR-GRI-5G", price: 495000, stock: 8 },
    ],
    stock: 68,
    isFeatured: true,
    isOffer: false,
    rating: 4.9,
    reviewsCount: 28,
    specs: {
      "Rendimiento": "25 a 30 m² por galón a 2 manos",
      "Tiempo de secado": "1 hora al tacto / 4 horas para segunda mano",
      "Garantía del fabricante": "5 años de protección exterior",
    },
    tags: ["pintura", "koraza", "pintuco", "impermeable", "fachada"],
    createdAt: "2026-08-04T09:00:00Z",
    updatedAt: "2026-08-25T11:00:00Z",
  },
  {
    id: "prod-cerradura-digital-yale",
    name: "Cerradura Digital de Seguridad Yale Smart Touch",
    slug: "cerradura-digital-de-seguridad-yale-smart-touch",
    description: "Cerradura inteligente con teclado táctil, lector de huella dactilar biométrico ultra rápido y llave mecánica de emergencia. Apta para puertas de madera y metal.",
    category: "cerrajeria-herrajes",
    categoryName: "Cerrajería y Herrajes",
    brand: "Yale",
    sku: "YDM-3109-PLUS",
    basePrice: 620000,
    originalPrice: 699000,
    images: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: true,
    variants: [
      { id: "v-negro", name: "Negro Mate Titanium", sku: "YDM-BLK", price: 620000, stock: 10 },
      { id: "v-plata", name: "Níquel Satinado", sku: "YDM-SIL", price: 620000, stock: 7 },
    ],
    stock: 17,
    isFeatured: true,
    isOffer: true,
    rating: 4.8,
    reviewsCount: 21,
    specs: {
      "Métodos de apertura": "Huella dactilar, Código PIN, Llave de seguridad",
      "Alimentación": "4 Baterías AA (Duración aprox. 12 meses)",
      "Espesor de puerta": "35mm a 80mm",
      "Garantía": "2 Años Yale Oficial",
    },
    tags: ["cerradura", "yale", "seguridad", "digital", "smart"],
    createdAt: "2026-08-10T15:00:00Z",
    updatedAt: "2026-08-23T18:00:00Z",
  },
  {
    id: "prod-reflector-led-solar-100w",
    name: "Reflector LED Solar 100W con Sensor de Movimiento y Control",
    slug: "reflector-led-solar-100w-con-sensor-de-movimiento-y-control",
    description: "Reflector de iluminación exterior con panel solar monocristalino integrado, batería de litio LiFePO4 de larga vida y control remoto. Protección IP66 contra lluvia y polvo.",
    category: "electricidad-iluminacion",
    categoryName: "Electricidad e Iluminación",
    brand: "Sylvania",
    sku: "REF-SOL-100",
    basePrice: 145000,
    images: [
      "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 45,
    isFeatured: false,
    isOffer: true,
    rating: 4.7,
    reviewsCount: 15,
    specs: {
      "Potencia Lumínica": "100W LED (1200 Lúmenes)",
      "Autonomía": "10-12 horas continuas con carga completa",
      "Protección": "IP66 impermeable",
      "Incluye": "Soporte metálico, tornillería, panel y control remoto",
    },
    tags: ["iluminacion", "solar", "led", "sylvania", "exterior"],
    createdAt: "2026-08-12T13:00:00Z",
    updatedAt: "2026-08-24T19:00:00Z",
  },
  {
    id: "prod-cemento-gris-argos",
    name: "Cemento Gris Uso General Argos (Bulto 50 Kg)",
    slug: "cemento-gris-uso-general-argos-bulto-50kg",
    description: "Cemento Portland de uso general de excelente trabajabilidad y resistencia para vigas, columnas, pisos, mampostería y mezclas de concreto de alto rendimiento.",
    category: "construccion",
    categoryName: "Construcción",
    brand: "Argos",
    sku: "CEM-ARG-50",
    basePrice: 32500,
    images: [
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
    ],
    hasVariants: false,
    variants: [],
    stock: 500,
    isFeatured: true,
    isOffer: false,
    rating: 5.0,
    reviewsCount: 88,
    specs: {
      "Peso": "50 Kilogramos por saco",
      "Tipo": "Portland Tipo UG (Uso General)",
      "Norma": "NTC 121 / ASTM C1157",
    },
    tags: ["cemento", "argos", "construccion", "obra"],
    createdAt: "2026-08-01T07:00:00Z",
    updatedAt: "2026-08-25T07:00:00Z",
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1001",
    orderNumber: "MH-2026-1001",
    customer: {
      name: "Carlos Mario Restrepo",
      phone: "3104567890",
      city: "Medellín",
      address: "Calle 45 # 78-22, Laureles",
      notes: "Por favor enviar en horas de la mañana",
    },
    items: [
      {
        productId: "prod-taladro-percutor-dewalt",
        productName: "Taladro Percutor Inalámbrico 20V DeWalt Brushless",
        slug: "taladro-percutor-inalambrico-20v-dewalt-brushless",
        sku: "DCD778-STD",
        image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
        price: 589000,
        quantity: 1,
        variantId: "v1",
        variantName: "Kit Estándar (2 Baterías 2.0Ah + Maletín)",
        maxStock: 12,
      },
      {
        productId: "prod-juego-llaves-stanley",
        productName: "Juego de Llaves Mixtas Métricas y Pulgadas Stanley",
        slug: "juego-de-llaves-mixtas-metricas-y-pulgadas-stanley-20-piezas",
        sku: "STMT74108",
        image: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80",
        price: 165000,
        quantity: 2,
        maxStock: 25,
      },
    ],
    subtotal: 919000,
    total: 919000,
    status: "completado",
    channel: "whatsapp_web",
    createdAt: "2026-08-24T15:20:00Z",
    updatedAt: "2026-08-24T17:40:00Z",
  },
  {
    id: "ord-1002",
    orderNumber: "MH-2026-1002",
    customer: {
      name: "Constructora Andes SAS",
      phone: "3148901234",
      city: "Bello",
      address: "Cra 50 # 32-10, Bodega 4",
      notes: "Factura electrónica con NIT 900.876.543-1",
    },
    items: [
      {
        productId: "prod-cemento-gris-argos",
        productName: "Cemento Gris Uso General Argos (Bulto 50 Kg)",
        slug: "cemento-gris-uso-general-argos-bulto-50kg",
        sku: "CEM-ARG-50",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80",
        price: 32500,
        quantity: 50,
        maxStock: 500,
      },
    ],
    subtotal: 1625000,
    total: 1625000,
    status: "atendido",
    channel: "whatsapp_web",
    createdAt: "2026-08-25T09:10:00Z",
    updatedAt: "2026-08-25T10:15:00Z",
  },
  {
    id: "ord-1003",
    orderNumber: "MH-2026-1003",
    customer: {
      name: "Andrea Gómez",
      phone: "3207788990",
      city: "Envigado",
      address: "Transversal 39 Sur # 25-18",
      notes: "Dejar en portería si no me encuentro",
    },
    items: [
      {
        productId: "prod-cerradura-digital-yale",
        productName: "Cerradura Digital de Seguridad Yale Smart Touch",
        slug: "cerradura-digital-de-seguridad-yale-smart-touch",
        sku: "YDM-BLK",
        image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
        price: 620000,
        quantity: 1,
        variantId: "v-negro",
        variantName: "Negro Mate Titanium",
        maxStock: 10,
      },
    ],
    subtotal: 620000,
    total: 620000,
    status: "pendiente",
    channel: "whatsapp_web",
    createdAt: "2026-08-25T18:45:00Z",
    updatedAt: "2026-08-25T18:45:00Z",
  },
];